### PR TITLE
Prevent hashing strings.

### PR DESCRIPTION
**Pull request by jamen**
See https://github.com/emilbayes/blake2b/issues/5

The `Buffer` fix is because:

image

But did you do it this interesting way for a reason?

### CODE REVIEW

**Comment by emilbayes** [comment]
Thanks! The `new Buffer` is actually from a autogenerated file, so I will remove that part and regenerate the file after this PR

**Comment by emilbayes** [comment]
This is merged into master now (by hand). Thanks! :)

**Comment by emilbayes** [comment]
Released as 2.1.0

**Comment by jamen** [comment]
Thank you 😄

**Pull request closed without merging**
